[workspace]
resolver = "2"

members = [
    "glue",
    "ingress",
    "nanoservices/core",
    "nanoservices/dal",
    "ingress/frontend/rust-interface",
    "nanoservices/networking/actix_server"
]

