[package]
name = "to-do-core"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
to-do-dal = {path = "../dal", features = ["json-file"]}
serde = { version="1.0.197", features = ["derive"]}

[features]